version: "3"
services:
  mysql:
    container_name: mysql
    platform: linux/x86_64
    build: ./mysql/
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/db:/docker-entrypoint-initdb.d
      - ./mysql/conf.d:/etc/mysql/conf.d
    env_file:
      - ./mysql/local.env
    tty: true
  app:
    depends_on:
      - mysql
    container_name: fast_api
    platform: linux/x86_64
    build: ./app
    restart: unless-stopped
    tty: true
    volumes:
      - ./app:/app
    ports:
      - 2020:2020
    env_file:
      - ./app/local.env
